# promise的理解和使用
## promise是什么？
### 理解
* 1、抽象表达：一门新的技术，是js中进行异步编程的新的解决方案，旧方案是单纯使用回调函数
* 2、具体表述：
*   （1）、从语法上来说，Promise是一个构造函数；
*   （2）、从功能上来说，Promise实例化对象用来封装一个异步操作，并可以获取成功/失败的结果值。
### 异步操作
* fs 文件操作
* 数据库操作
* AJAX
* 定时器

## 为什们要用Promise?
### 指定回调函数的方式更加灵活
* 1、旧的，必须在启动异步任务之前指定
* 2、promise,启动异步任务 =》返回Promise对象 =》 给Promise对象绑定回调函数（甚至可以在异步任务结束后指定/多个）
### 支持链式调用。可以解决回调地狱的问题
* 1、什么是回调地狱？————回调函数嵌套调用，外部回调函数执行的结果是嵌套的回调函数执行的条件
* 2、回调地狱的缺点？————不便于阅读、不便于异常处理
* 3、解决方案？————promise链式调用

## Promise的状态改变
### Promise的状态
* 实例对象中的一个属性 [PromiseState]
* pending 未决定的，挂起中的
* resolved/fullfilled 成功
* rejected 失败
* PromiseState只有两种变化的可能
* 1、pending变为resolved
* 2、pending变为rejectd
  只有这两种，且一个promise对象只能改变一次，无论变为成功还是失败，都会有一个结果数据，成功的结果数据一般称为value,失败的结果数据一般称为reason
### Promise对象的值
* 实例对象中的另一个属性 [PromiseResult]
* 保存着对象 成功/失败 的结果
* resolve()和reject()可以改变这个属性的值

## 如何使用Promise
### API
#### Promise构造函数：Promise(excutor){}
* (1)、excute函数：执行器 (resolve, reject) => {}，promise的函数参数对象称为执行器函数。
* (2)、resolve函数：内部定义成功时调用的函数 value => {}
* (3)、reject函数：内部定义失败时调用的函数 reason => {}
* excute执行器，会在实例化promise对象时立即同步调用，异步操作在执行器中执行

#### Promise.prototype.then方法：(onResolved, onRejected) => {}
* (1)、onResolved 函数：成功的回调函数 (value) => {}
* (2)、onRejected 函数：失败的回调函数 (reason) => {}
* 指定用于得到成功value的成功回调和用于得到失败reason的失败回调返回一个新的promise对象

#### Promise.proptype.catch 方法：(onRejected) => {}
* (1)、onRejected 函数：失败的回调函数 (reason) => {}

#### Promise.resolve 方法：(value) => {}，属于函数对象的方法，不属于实例的方法
* (1)、value: 成功的数据或promise对象
* 返回一个成功/失败的promise对象

#### Promise.reject 方法：(reason) => {}，属于函数对象的方法，不属于实例的方法
* (1)、reason 失败的原因
* 返回一个失败的promise对象

#### Promise.all 方法：(promise) => {}，属于函数对象的方法，不属于实例的方法
* (1) promise: 包含n个promise的数组
* 返回一个新的promise,只有新的promise成功才能成功，只要一个失败了就直接失败

#### Promise.race() 方法：(promise) => {}，属于函数对象的方法，不属于实例的方法
* (1)、promise: 包含n个prmise的数组
* 返回一个新的promise,第一个完成的promise的结果状态就是最终的结果状态

### promise的几个关键问题
#### 如何改变promise的状态？改变promise状态的三种方法
* (1)、resolve(value): 如果当前是pengding就会变成resolved(fulfilled)
* (2)、rejece(value): 如果当前是pengding就会变成rejected
* (3)、抛出异常：如果当前是pengding就会变成rejected

#### 一个promise指定多个成功/失败回调函数，都会调用吗？
* 当promise改变为对应状态时都会调用

#### 改变promise状态和指定回调函数(不是执行回调函数)谁先谁后？
* (1)、都有可能，正常情况是先指定回调函数再改变状态，但也有可能是先改变状态再指定回调
* (2)、如何先改变状态再指定回调？
*      在执行器中直接调用resolve()/reject()
*      延长更长的时间才调用then()
* (3)、什么时候才能得到数据？
*      如果先指定的回调，那当状态发生改变时，回调函数就会调用，得到数据
*      如果先改变状态，那当指定回调时，回调函数就会调用，得到数据

#### promise.then()返回的新promise的结果状态由什么决定？
* (1)、简单表述：由 then() 指定的回调函数执行的结果决定
* (2)、详细表达：
*      a、如果抛出异常，新 promise 变为 rejected,reason 为抛出的异常；
*      b、如果返回的是非Promise的任意值，新promise变为resolved,value为返回的值；
*      c、如果返回的是另一个新promise,此promise的结果就会变成新promise的结果；

#### promise 如何串联多个操作任务？
* (1)、promise 的 then()返回一个新的promise,可以看成 then() 的链式调用
* (2)、通过 then 的链式调用串联多个同步、异步任务

#### promise 异常穿透？
* (1)、当使用promise的then链式调用时，可以在最后指定失败的回调；
* (2)、前面在任何操作出了异常，都会传到最后失败的回调中处理

#### 中断promise链？
* (1)、当使用promise的then链式调用时，在中间中断，不在调用后面的回调函数；
* (2)、办法：在回调函数中返回一个pending状态的promise对象；

# async与await
## async函数
* 函数的返回值是promise对象
* promise对象的结果有async函数执行的返回值决定

## await函数
* await右侧的表达式一般是promise类型的对象，但也可以是其它的值
* 如果表达式是promise对象，await返回的是promise成功的【值】PromiseResult
* 如果表达式是其他值，直接将此值作为await的返回值

## 注意
* await必须写在async函数中，但是async函数中可以没有await
* 如果await的promise失败了，就会抛出异常，需要通过try...catch捕获处理

